version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=agenda'
      - 'MYSQL_PASSWORD=BHU*nji9'
      - 'MYSQL_ROOT_PASSWORD=BHU*nji9'
      - 'MYSQL_USER=banco'
    ports:
      - '3306'
  spring-app:
    build: .
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/agenda'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=banco'
  front-app:
    image: 'jhonyamn/agendafront:1.0'
    ports:
    - '5173:5173'
    environment:
      - 'API_URL=http://spring-app:8080'
    